# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Pinder' do
   pod 'ZLSwipeableView'
   pod 'AFNetworking', '~> 2.6'
   pod 'MBProgressHUD', '~> 0.9'
end

target 'PinderTests' do

end

